version: '3.8'

services:
  usuarios-api:
    build: .
    container_name: usuarios_api_node
      
    environment:
      - NODE_ENV=development
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_APPLICATION_NAME=microservico-usuarios
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USERNAME}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PASSWORD}
    networks:
      - microservices-net


networks:
  microservices-net:
    external: true